name: Integration Test

on:
  workflow_dispatch:
    ## The tests take a long time to run and can be potentially quite costly, so set it to run manually

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dynamicCoordinates: [true, false]
    defaults:
      run:
        working-directory: ./tools/integration
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './tools/integration/'

      - name: Install dependencies
        run: npm ci

      - name: Run tests on tools
        run: npm test
        
      - name: Trigger harvest and verify completion
        run: DYNAMIC_COORDINATES=${{ matrix.dynamicCoordinates }} npm run e2e-test-harvest

      - name: Verify service functions
        run: DYNAMIC_COORDINATES=${{ matrix.dynamicCoordinates }} npm run e2e-test-service
