name: Integration Test

on:
  workflow_dispatch:
    inputs:
      baseFolderPath:
        description: 'Base folder path for diffs'
        required: true
        default: 'diffs'
      dynamicCoordinates:
        description: 'Array of booleans for dynamic coordinates (e.g., [true, false])'
        required: true
        default: '[true, false]'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dynamicCoordinates: ${{ fromJson(github.event.inputs.dynamicCoordinates) }}
    defaults:
      run:
        working-directory: ./tools/integration
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './tools/integration/'

      - name: Install dependencies
        run: npm ci

      - name: Run tests on tools
        run: npm test
        
      - name: Trigger harvest and verify completion
        run: DYNAMIC_COORDINATES=${{ matrix.dynamicCoordinates }} npm run e2e-test-harvest

      - name: Verify service functions
        run: DYNAMIC_COORDINATES=${{ matrix.dynamicCoordinates }} npm run e2e-test-service

      - name: Generate structured diffs
        run: npm run definitions-diff ${{ github.event.inputs.baseFolderPath }}

      - name: Upload diffs artifact
        uses: actions/upload-artifact@v4
        with:
          name: diffs-${{ matrix.dynamicCoordinates == 'true' && 'dynamic' || 'static' }}
          path: ./tools/integration/${{ github.event.inputs.baseFolderPath }}
